version: '3'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your password
      POSTGRES_DB: database name
    ports:
      - "5432:5432"

  # Express App Service
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: database name
      PGPASSWORD: your password
      PGPORT: 5432
